"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$fill\
$kubernetes\
$aws\
$time\n \
[󱞪 ](fg:iris)
"""

palette = "rose-pine"

[palettes.rose-pine]
overlay = '#403d52'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ebbcba'
pine = '#31748f'
foam = '#9ccfd8'
iris = '#c4a7e7'

[username]
disabled = false
format = "[\ue0d4](fg:rose)[  $user]($style)"
show_always = true
style_root = "bg:rose fg:overlay"
style_user = "bg:rose fg:overlay"

[hostname]
disabled = false
format = "[@$hostname ]($style)[\ue0b0](fg:rose)"
style = "bg:rose fg:overlay"
ssh_only = false

[directory]
format = "[\ue0d4](fg:overlay)[ $path ]($style)[\ue0b0](fg:overlay)"
style = "bg:overlay fg:gold"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
Documents = "󰈙"
Downloads = " "
Music = " "
Pictures = " "

[fill]
style = "fg:overlay"
symbol = " "

[git_branch]
format = "[\ue0d4](fg:rose)[ $symbol $branch ]($style)[\ue0b0](fg:rose)"
style = "bg:rose fg:overlay"
symbol = ""

[git_status]
disabled = false
style = "bg:overlay fg:love"
format = "[\ue0d4](fg:overlay)([ $all_status$ahead_behind]($style))[\ue0b0](fg:overlay)"
up_to_date = '[✓](bg:overlay fg:iris)'
untracked = '[󰡯 $count ](bg:overlay fg:love)'
stashed = '[󰜦 $count ](bg:overlay fg:pine)'
modified = '[ $count ](bg:overlay fg:rose)'
renamed = '[»$count ](bg:overlay fg:iris)'
deleted = '[󰆴$count ](style)'
staged = '[󱡠 $count ](bg:overlay fg:foam)'
ahead = '[󰶼$count ](bg:overlay fg:foam)'
diverged = '[\[](bg:overlay fg:iris)[⇡\(${ahead_count}\)](bg:overlay fg:foam)[⇣\(${behind_count}\)](bg:overlay fg:rose)[\]](bg:overlay fg:iris)'
behind = '[󰶹$count ](bg:overlay fg:rose)'

[aws]
disabled = false
format = "[](fg:rose)[ \uef2c ]($style)[$region]($style)[$duration ]($style)[\ue0d2](fg:rose)"
style = "bg:rose fg:overlay"
force_display = true

[kubernetes]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)($style)[ $context ]($style)[\ue0d2](fg:overlay)"
disabled = false
symbol = "󱃾 "
contexts = [
  { context_pattern = "arn:aws:eks:us-east-1:196375513521:cluster/production-corp", context_alias = "󱃾 production"},
]

[time]
disabled = false
format = "[](fg:overlay)[ $time 󰣇 ]($style)(fg:rose)[\ue0d2](fg:overlay)"
style = "bg:overlay fg:pine"
time_format = "%I:%M%P"
use_12hr = true

# Languages
[c]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[ \ue0d2](fg:overlay)"
disabled = false
symbol = " "

[golang]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[\ue0d2](fg:overlay)"
disabled = false
symbol = " "

[nodejs]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[\ue0d2](fg:overlay)"
disabled = false
symbol = "󰎙 "

[php]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[\ue0d2](fg:overlay)"
disabled = false
symbol = " "

[lua]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[\ue0d2](fg:overlay)"
disabled = false
symbol = " "

[rust]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[\ue0d2](fg:overlay)"
disabled = false
symbol = ""

[python]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay)"
disabled = false
symbol = ' '
